FROM arm32v7/ubuntu:disco

COPY --from=xmonit/arm32v7-builder qemu-arm-static /usr/bin

RUN apt-get -y update
RUN apt-get -y upgrade

RUN apt-get -y install vim wget
RUN apt-get -y install build-essential
RUN apt-get -y install cmake git
RUN apt-get -y install openssl libssl-dev
#RUN apt-get -y install libpoco-dev

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

WORKDIR /src
RUN git clone -b master https://github.com/pocoproject/poco.git

WORKDIR /src/poco
RUN git checkout poco-1.9.4-release 

RUN mkdir cmake-build
WORKDIR /src/poco/cmake-build

RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make install
